baseurl = "https://blogs.afnan.codes/"
title = "Afnan K Salal"
theme = "PaperMod"

# Prevent raw HTML errors
ignoreLogs = ["warning-goldmark-raw-html"]

[Params]
    mainSections = ["post"]
    github = "https://github.com/afnanksalal"
    twitter = "https://twitter.com/afnanksalal"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Optional but recommended for modern Hugo
[outputs]
  home = ["HTML", "RSS", "JSON"]
